### PR TITLE
Adjust to JuliaLang/julia#53219

### LINKED ISSUE #552: `type CodeInfo has no field rettype` on Julia's master branch
Sorry, I don't have an MWE yet, but I ran into this error while testing some modifications to Julia's master branch:
```julia
ERROR: type CodeInfo has no field rettype
Stacktrace:
  [1] getproperty(ci::Core.CodeInfo, s::Symbol)
    @ Base ./deprecated.jl:330
  [2] cthulhu_typed(io::IOContext{…}, debuginfo::Symbol, src::Core.CodeInfo, rt::Any, exct::Any, effects::Core.Compiler.Effects, mi::Core.MethodInstance; iswarn::Bool, hide_type_stable::Bool, optimize::Bool, pc2remarks::Nothing, pc2effects::Nothing, pc2excts::Nothing, inline_cost::Bool, type_annotations::Bool, annotate_source::Bool, inlay_types_vscode::Bool, diagnostics_vscode::Bool, jump_always::Bool, interp::Cthulhu.CthulhuInterpreter)
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/codeview.jl:185
  [3] cthulhu_typed(::IOContext{…}, ::Cthulhu.DInfo.DebugInfo, ::Core.CodeInfo, ::Vararg{…}; kwargs::@Kwargs{…})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/codeview.jl:105
  [4] (::Cthulhu.var"#92#99"{…})(lambda_io::IOContext{…})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:521
  [5] stringify(f::Any, context::IOContext{Base.TTY})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/ui.jl:92
  [6] 
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:520
  [7]  (repeats 3 times)
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:647
  [8] 
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:647
  [9] _descend(term::REPL.Terminals.TTYTerminal, interp::Cthulhu.CthulhuInterpreter, mi::Core.MethodInstance; kwargs::@Kwargs{iswarn::Bool})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:791
 [10] _descend(term::REPL.Terminals.TTYTerminal, args::Any; interp::Core.Compiler.NativeInterpreter, kwargs::@Kwargs{iswarn::Bool})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:807
 [11] __descend_with_error_handling(args::Any; terminal::Any, kwargs...)
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:222
 [12] _descend_with_error_handling(f::Any, argtypes::Any; kwargs::@Kwargs{iswarn::Bool})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:211
 [13] descend_code_typed(::Any, ::Vararg{Any}; kwargs::@Kwargs{})
    @ Cthulhu ~/Dropbox/JuliaPackages/Cthulhu.jl/src/Cthulhu.jl:169
 [14] top-level scope
    @ REPL[11]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> VERSION
v"1.12.0-DEV.120"
```

### PR DESCRIPTION
**Pull request by Keno**
These are the changes I was using locally when developing that branch to have basic Cthulhu functionality. It's likely additional changes are required to have Cthulhu fully functional.

- closes #552

### CODE REVIEW

File: TypedSyntax/src/node.jl [hunk 1]
```diff
@@ -306,15 +307,22 @@ end
 
 function getsrc(@nospecialize(f), @nospecialize(t))
     srcrts = code_typed(f, t; debuginfo=:source, optimize=false)
-    return only(srcrts)
+    src, rt = only(srcrts)
+    if hasfield(typeof(src), :parent)
+        mi = src.parent
+    else
+        mi = Base.method_instance(f, t)
+    end
```
Comment (topolarity) [inline TypedSyntax/src/node.jl:315]: I'm a bit uncertain about using a separate `method_instance` lookup than the one implicit in `code_typed`. That sounds like an opportunity for desynchronization.

However, I don't think we have a MI-based code_typed entry point yet so I don't believe there's another alternative.

Comment (Keno) [reply TypedSyntax/src/node.jl:315]: > However, I don't think we have a MI-based code_typed entry point yet

I think it would be reasonable to add one. I agree, it would be better to look up the method instance first and use that to query the source.

**Comment by topolarity** [comment]
Nightly still reports ~7 failing tests for me locally with the latest changes, but those seem to match the last CI: https://github.com/JuliaDebug/Cthulhu.jl/actions/runs/7857995905/job/21442465198

(from the last run before https://github.com/JuliaDebug/Cthulhu.jl/issues/541 started affecting us)

File: TypedSyntax/src/node.jl [hunk 2]
```diff
@@ -306,15 +307,22 @@ end
 
 function getsrc(@nospecialize(f), @nospecialize(t))
     srcrts = code_typed(f, t; debuginfo=:source, optimize=false)
-    return only(srcrts)
+    src, rt = only(srcrts)
+    if hasfield(typeof(src), :parent)
```
Comment (Keno) [inline TypedSyntax/src/node.jl:311]: `&& src.parent !== nothing`, since this field got added back

Comment (topolarity) [reply TypedSyntax/src/node.jl]: Oh I didn't realize that, will do

File: TypedSyntax/src/node.jl [hunk 3]
```diff
@@ -306,15 +307,22 @@ end
 
 function getsrc(@nospecialize(f), @nospecialize(t))
     srcrts = code_typed(f, t; debuginfo=:source, optimize=false)
-    return only(srcrts)
+    src, rt = only(srcrts)
+    if hasfield(typeof(src), :parent) && src.parent !== nothing
```
Comment (aviatesk) [inline TypedSyntax/src/node.jl:311]:
```suggestion
    if src.parent !== nothing
```
`codeinfo.parent` didn't get deleted.

File: TypedSyntax/src/node.jl [hunk 4]
```diff
@@ -306,15 +307,22 @@ end
...
+        mi = src.parent
+    else
+        mi = Base.method_instance(f, t)
+    end
+    return src, rt, mi
```
Comment (aviatesk) [inline TypedSyntax/src/node.jl:316]: Also, it seems to be confusing that methods with the same name return different type objects. I would like to extract `MethodInstance` lookup logic outside of this function rather than including it here.

File: TypedSyntax/src/node.jl (hunk 1 above)
Comment (aviatesk) [reply TypedSyntax/src/node.jl]: Implemented the refactoring at 707a1818d16ac3a2d9cecd7fc916b4ca70fada7b.

**Comment by aviatesk** [comment]
The nightly failures are all #541. Going to merge.
