### PR TITLE
fix #245: error in limited callinfo printing

### LINKED ISSUE #245: Error in printing
```
ERROR: MethodError: no method matching length(::Base.Iterators.Rest{Core.SimpleVector, Int64})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at ~/julia/usr/share/julia/base/abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, <:Union{StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}}}, Diagonal{T, <:StaticArrays.StaticVector{<:Any, T}}, LinearAlgebra.Hermitian{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.LowerTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, Symmetric{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.Transpose{T, <:Union{StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}}}, LinearAlgebra.UnitLowerTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.UnitUpperTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, LinearAlgebra.UpperTriangular{T, <:StaticArrays.StaticMatrix{<:Any, <:Any, T}}, StaticArrays.StaticVector{<:Any, T}, StaticArrays.StaticMatrix{<:Any, <:Any, T}, StaticArrays.StaticArray{<:Tuple, T}} where T) at ~/.julia/packages/StaticArrays/qd9eq/src/abstractarray.jl:1
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/julia/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:171
  ...
Stacktrace:
  [1] __show_limited(limiter::Cthulhu.TextWidthLimiter, name::String, tt::Base.Iterators.Rest{Core.SimpleVector, Int64}, rt::Any)
    @ Cthulhu ~/.julia/packages/Cthulhu/4Dylk/src/callsite.jl:211
  [2] show_callinfo(limiter::Cthulhu.TextWidthLimiter, ci::Cthulhu.MultiCallInfo)
    @ Cthulhu ~/.julia/packages/Cthulhu/4Dylk/src/callsite.jl:249
  [3] show(io::IOContext{IOBuffer}, c::Cthulhu.Callsite)
    @ Cthulhu ~/.julia/packages/Cthulhu/4Dylk/src/callsite.jl:292
  [4] (::Cthulhu.var"#26#27"{Cthulhu.Callsite, Bool, Bool, Tuple{Int64, Int64}})(io::IOBuffer)
    @ Cthulhu ~/.julia/packages/Cthulhu/4Dylk/src/ui.jl:18
  [5] sprint(::Function; context::Nothing, sizehint::Int64)
    @ Base ./strings/io.jl:114
```
I don't have a concrete reproducer, but hopefully this should help.

### PR DESCRIPTION
**Pull request by simeonschaub**

### CODE REVIEW

File: src/callsite.jl [hunk 1]
```diff
@@ -238,7 +238,7 @@ end
 
 function show_callinfo(limiter, ci::Union{MultiCallInfo, FailedCallInfo, GeneratedCallInfo})
     types = (ci.sig::DataType).parameters
-    ft, tt... = types
+    ft, tt = types[1], types[2:end]
```
Comment (simeonschaub) [inline src/callsite.jl:241]: I'll make a PR to base so that `tt` stays a `SimpleVector` here, but since that probably won't be backported to 1.7, we'll have to use this workaround instead.
